### ISSUE TITLE
Inverted graph

### ISSUE THREAD

**Issue by francisdb** [TheoBr/dogecoin-simulator#5]
Is it me or is this graph messed up?

<img width="322" alt="image" src="https://user-images.githubusercontent.com/161305/117792924-079e3700-b24c-11eb-9b88-26eb77197a15.png">

**Comment by francisdb** [comment]
also I expect the graph to be locked to 0 and not rescale all the time

**Comment by t3dotgg** [comment]
Sorry just saw this. Graph is "inverted" to indicate when price is doing well. Goes up when price is good, down when price is bad. Price is in DOGE/USD to make the y-axis readable.

Should probably have made this more clear, but it was a really quick and dirty side project. Open to suggestions on better axis, but otherwise I think this is the best I can do
